 version: '3.6'
 services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-starships
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql-starships
    environment:
      MYSQL_DATABASE: 'starships'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'